# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/sanmugavel/project_7/project_7.cache/wt [current_project]
set_property parent.project_path C:/Users/sanmugavel/project_7/project_7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/sanmugavel/project_7/project_7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/sanmugavel/project_7/project_7.srcs/sources_1/new/clock_divider.v
  C:/Users/sanmugavel/project_7/project_7.srcs/sources_1/new/doa_calculator.v
  C:/Users/sanmugavel/project_7/project_7.srcs/sources_1/new/energy_detector.v
  C:/Users/sanmugavel/project_7/project_7.srcs/sources_1/new/gunshot_trigger.v
  C:/Users/sanmugavel/project_7/project_7.srcs/sources_1/new/i2s_master.v
  C:/Users/sanmugavel/project_7/project_7.srcs/sources_1/new/i2s_receiver_4ch.v
  C:/Users/sanmugavel/project_7/project_7.srcs/sources_1/new/tdoa_estimator.v
  C:/Users/sanmugavel/project_7/project_7.srcs/sources_1/new/top_gunshot_system.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/sanmugavel/project_7/project_7.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/sanmugavel/project_7/project_7.srcs/constrs_1/new/cons.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_gunshot_system -part xc7a35ticpg236-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_gunshot_system.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_gunshot_system_utilization_synth.rpt -pb top_gunshot_system_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
